/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("tme.yajc.kotlin-application-conventions")
}

dependencies {
    implementation(project(":tic-tac-toe"))
    implementation(project(":checkers"))
}

application {
    // Define the main class for the application.
    mainClass.set("tme.yajc.app.AppKt")
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}